version: "3.8"
services:
  db:
    container_name: mssql_database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: 2D5wda5wRTG@wag21245awga63!
      ACCEPT_EULA: Y
    volumes:
      - mssql_data:/var/opt/mssql
  api:
    image: danielkrich147/keeperwebapi:1.0.0
    ports:
      - '80-85:80'
    volumes:
      - keeper_uploads:/app/uploads

volumes:
  keeper_uploads:
  mssql_data:
